# Generated by Django 6.0.2 on 2026-02-18 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoglioMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese', models.IntegerField(verbose_name='Mese')),
                ('anno', models.IntegerField(verbose_name='Anno')),
                ('giorno_1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_3', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_4', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_5', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_6', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_7', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_8', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_9', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_10', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_11', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_12', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_13', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_14', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_15', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_16', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_17', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_18', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_19', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_20', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_21', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_22', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_23', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_24', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_25', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_26', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_27', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_28', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_29', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_30', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('giorno_31', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fogli_presenze', to='anagrafica.dipendente', verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Foglio Presenze Mensile',
                'verbose_name_plural': 'Fogli Presenze Mensili',
                'unique_together': {('dipendente', 'mese', 'anno')},
            },
        ),
    ]
