# Generated by Django 6.0.2 on 2026-02-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessioneImportazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Import')),
                ('nome_file', models.CharField(max_length=255, verbose_name='File Sorgente')),
                ('totale_dipendenti', models.IntegerField(default=0, verbose_name='N. Dipendenti')),
                ('costo_totale_periodo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Totale Azienda')),
            ],
            options={
                'verbose_name': 'Sessione di Importazione',
                'verbose_name_plural': 'Storico Importazioni ETL',
            },
        ),
        migrations.CreateModel(
            name='RecordStoricoDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricola', models.CharField(max_length=50)),
                ('nominativo', models.CharField(max_length=255)),
                ('lordo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_aziendale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netto_stimato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='importer.sessioneimportazione')),
            ],
            options={
                'unique_together': {('sessione', 'matricola')},
            },
        ),
    ]
