# Generated by Django 6.0.2 on 2026-02-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordstoricodipendente',
            options={'verbose_name': 'Record Storico'},
        ),
        migrations.AlterModelOptions(
            name='sessioneimportazione',
            options={'verbose_name': 'Sessione ETL', 'verbose_name_plural': 'Storico Mapper ETL'},
        ),
        migrations.RenameField(
            model_name='sessioneimportazione',
            old_name='nome_file',
            new_name='nome_file_principale',
        ),
        migrations.AlterUniqueTogether(
            name='recordstoricodipendente',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='costo_aziendale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='lordo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='netto_stimato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='costo_totale_periodo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='totale_dipendenti',
            field=models.IntegerField(default=0),
        ),
    ]
