# Generated by Django 6.0.2 on 2026-02-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_alter_recordstoricodipendente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profilo', models.CharField(default='Ranocchi Standard', max_length=100, unique=True)),
                ('mappatura_json', models.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='recordstoricodipendente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sessioneimportazione',
            options={},
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='netto_stimato',
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='codice_azienda',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='ragione_sociale',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='nome_file_principale',
            field=models.CharField(max_length=255),
        ),
    ]
