# Generated by Django 6.0.2 on 2026-02-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_configurazionemapper_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurazionemapper',
            options={'verbose_name': 'Profilo Mappatura', 'verbose_name_plural': 'Profili Mappatura'},
        ),
        migrations.AlterModelOptions(
            name='recordstoricodipendente',
            options={'verbose_name': 'Record Storico Dipendente', 'verbose_name_plural': 'Records Storici'},
        ),
        migrations.AlterModelOptions(
            name='sessioneimportazione',
            options={'verbose_name': 'Sessione di Importazione', 'verbose_name_plural': 'Storico Importazioni ETL'},
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='data_assunzione',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data assunzione'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='data_cessazione',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data cessazione'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='data_cessazione_prevista',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data cessazione prevista'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='dati_completi_json',
            field=models.JSONField(default=dict, verbose_name='Dati Integrali'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='ex_fest_residuo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ExFes Residuo'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='ferie_residue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ferie Residue'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='livello',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Livello'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='netto_stimato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Netto Busta'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='perc_part_time',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Perc. Part time'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='permessi_residui',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Permessi Residui'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='qualifica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualifica'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='rol_residuo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rol Residuo'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='tipo_contratto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo det/indet'),
        ),
        migrations.AlterField(
            model_name='configurazionemapper',
            name='mappatura_json',
            field=models.JSONField(verbose_name='Mappatura Colonne'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='codice_azienda',
            field=models.CharField(max_length=50, verbose_name='Codice Azienda'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='costo_aziendale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Aziendale'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='lordo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lordo Mensile'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='matricola',
            field=models.CharField(max_length=50, verbose_name='Matricola'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='nominativo',
            field=models.CharField(max_length=255, verbose_name='Nominativo'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='ragione_sociale',
            field=models.CharField(max_length=255, verbose_name='Ragione Sociale'),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='costo_totale_periodo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Totale Periodo'),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='data_operazione',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Importazione'),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='nome_file_principale',
            field=models.CharField(max_length=255, verbose_name='File Sorgente Principale'),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='totale_dipendenti',
            field=models.IntegerField(default=0, verbose_name='N. Dipendenti Totali'),
        ),
        migrations.AlterUniqueTogether(
            name='recordstoricodipendente',
            unique_together={('sessione', 'codice_azienda', 'matricola')},
        ),
    ]
