# Generated by Django 6.0.2 on 2026-02-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_alter_configurazionemapper_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 1'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 10'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_11',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 11'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 12'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_13',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 13'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_14',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 14'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 15'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_16',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 16'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_17',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 17'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 18'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 2'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 3'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 4'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 5'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 6'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 7'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 8'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 9'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='retribuzione_di_fatto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retribuzione di Fatto'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='tipo_retribuzione',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Retribuzione'),
        ),
    ]
