# Generated by Django 6.0.2 on 2026-02-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_recordstoricodipendente_elemento_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='data_assunzione',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='data_cessazione',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='data_cessazione_prevista',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_10',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_11',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_12',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_13',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_14',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_15',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_16',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_17',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_18',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_6',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_7',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_8',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='elemento_9',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='ex_fest_residuo',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='livello',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='permessi_residui',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='rol_residuo',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='tipo_contratto',
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='inail_ditta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='INAIL Ditta'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='inps_ditta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='INPS Ditta'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='ore_ordinarie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ore Ord.'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='ore_straordinarie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ore Extra'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='tfr_quota_mese',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='TFR Mese'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='codice_azienda',
            field=models.CharField(max_length=50, verbose_name='Cod. Azienda'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='costo_aziendale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Totale'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='dati_completi_json',
            field=models.JSONField(default=dict, verbose_name='Dati Integrali (JSON)'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='ferie_residue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='perc_part_time',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='PT %'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='qualifica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='retribuzione_di_fatto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Paga Oraria/Mensile'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='tipo_retribuzione',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Ret.'),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='costo_totale_periodo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Totale Stimato'),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='nome_file_principale',
            field=models.CharField(max_length=255, verbose_name='File Sorgente'),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='totale_dipendenti',
            field=models.IntegerField(default=0, verbose_name='N. Dipendenti'),
        ),
    ]
