# Generated by Django 6.0.2 on 2026-02-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_remove_recordstoricodipendente_data_assunzione_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='ferie_residue',
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_11',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_13',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_14',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_16',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_17',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='elemento_9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='exfes_res',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ExFes Res.'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='ferie_res',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ferie Res.'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='perm_res',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Perm. Res.'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='rol_res',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rol Res.'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='ore_ordinarie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ore Ord. (L+A)'),
        ),
    ]
