# Generated by Django 6.0.2 on 2026-02-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0007_remove_recordstoricodipendente_ferie_residue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='exfes_res',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='ferie_res',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='perm_res',
        ),
        migrations.RemoveField(
            model_name='recordstoricodipendente',
            name='rol_res',
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='data_assunzione',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data assunzione'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='data_cessazione',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data cessazione'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='data_cessazione_prevista',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data cessazione prevista'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='ex_fest_maturato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ExFes Maturato'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='ex_fest_residuo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ExFes Residuo'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='ferie_maturate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ferie Maturate'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='ferie_residue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ferie Residue'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='livello',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Livello'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='permessi_maturati',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Permessi Maturati'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='permessi_residui',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Permessi Residui'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='rol_maturato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rol Maturato'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='rol_residuo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rol Residuo'),
        ),
        migrations.AddField(
            model_name='recordstoricodipendente',
            name='tipo_contratto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo det/indet'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='codice_azienda',
            field=models.CharField(max_length=50, verbose_name='Codice Azienda'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='costo_aziendale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Aziendale'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='dati_completi_json',
            field=models.JSONField(default=dict, verbose_name='Dati Integrali'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 1'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 10'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_11',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 11'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 12'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_13',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 13'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_14',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 14'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 15'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_16',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 16'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_17',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 17'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 18'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 2'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 3'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 4'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 5'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 6'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 7'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 8'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='elemento_9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elemento 9'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='ore_ordinarie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ore Ordinarie'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='ore_straordinarie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ore Straordinarie'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='perc_part_time',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Perc. Part time'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='qualifica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualifica'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='retribuzione_di_fatto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retribuzione di Fatto'),
        ),
        migrations.AlterField(
            model_name='recordstoricodipendente',
            name='tipo_retribuzione',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Retribuzione'),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='costo_totale_periodo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Totale Periodo'),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='nome_file_principale',
            field=models.CharField(max_length=255, verbose_name='File Sorgente Principale'),
        ),
        migrations.AlterField(
            model_name='sessioneimportazione',
            name='totale_dipendenti',
            field=models.IntegerField(default=0, verbose_name='N. Dipendenti Totali'),
        ),
    ]
