# Generated by Django 6.0.2 on 2026-02-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCNL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Contratto (es. Terziario)')),
                ('divisore_orario_standard', models.DecimalField(decimal_places=2, default=173.0, max_digits=6, verbose_name='Divisore Orario')),
                ('magg_straordinario', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='% Magg. Straordinario')),
            ],
            options={
                'verbose_name_plural': '2. Schede CCNL',
            },
        ),
        migrations.CreateModel(
            name='ConfigurazioneMappatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_software', models.CharField(help_text='Es: Ranocchi GIS Standard', max_length=100)),
                ('ana_riga_inizio', models.IntegerField(default=1, verbose_name='ANA: Riga Inizio Dati')),
                ('ana_col_azienda_cod', models.IntegerField(default=0, verbose_name='ANA: Col. Codice Azienda')),
                ('ana_col_azienda_ragione', models.IntegerField(default=2, verbose_name='ANA: Col. Ragione Sociale')),
                ('ana_col_matricola', models.IntegerField(default=4, verbose_name='ANA: Col. Matricola')),
                ('ana_col_nominativo', models.IntegerField(default=5, verbose_name='ANA: Col. Cognome Nome')),
                ('ana_col_indirizzo', models.IntegerField(default=6, verbose_name='ANA: Col. Indirizzo')),
                ('ana_col_comune', models.IntegerField(default=7, verbose_name='ANA: Col. Comune')),
                ('ana_col_qualifica', models.IntegerField(default=8, verbose_name='ANA: Col. Qualifica')),
                ('ana_col_tipo_contratto', models.IntegerField(default=9, verbose_name='ANA: Col. Tempo Det/Indet')),
                ('ana_col_perc_part_time', models.IntegerField(default=11, verbose_name='ANA: Col. % Part-Time')),
                ('ana_col_assunzione', models.IntegerField(default=12, verbose_name='ANA: Col. Data Assunzione')),
                ('ana_col_cessazione', models.IntegerField(default=13, verbose_name='ANA: Col. Data Cessazione')),
                ('ana_col_termine', models.IntegerField(default=14, verbose_name='ANA: Col. Fine Prevista/Proroga')),
                ('ret_riga_inizio', models.IntegerField(default=2, verbose_name='RET: Riga Inizio Dati')),
                ('ret_col_matricola', models.IntegerField(default=6, verbose_name='RET: Col. Matricola')),
                ('ret_col_tipo_paga', models.IntegerField(default=11, verbose_name='RET: Col. Tipo Retribuzione')),
                ('ret_col_lordo_fatto', models.IntegerField(default=30, verbose_name='RET: Col. Lordo AE / Tariffa Oraria')),
                ('ret_col_elementi_start', models.IntegerField(default=12, verbose_name='RET: Col. Inizio Elementi 1-8')),
                ('sta_col_matricola', models.IntegerField(default=6, verbose_name='STA: Col. Matricola')),
                ('sta_col_inps', models.IntegerField(default=33, verbose_name='STA: Col. INPS Ditta (AH)')),
                ('sta_col_inail', models.IntegerField(default=34, verbose_name='STA: Col. INAIL Ditta (AI)')),
                ('sta_col_tfr', models.IntegerField(default=28, verbose_name='STA: Col. TFR')),
                ('rat_col_matricola', models.IntegerField(default=5, verbose_name='RAT: Col. Matricola')),
                ('rat_col_ferie_ap', models.IntegerField(default=11, verbose_name='RAT: Col. Ferie Residue (L)')),
                ('rat_col_permessi_ap', models.IntegerField(default=14, verbose_name='RAT: Col. Permessi Residui (O)')),
                ('rat_col_rol_ap', models.IntegerField(default=18, verbose_name='RAT: Col. ROL (S)')),
                ('rat_col_exfest_ap', models.IntegerField(default=22, verbose_name='RAT: Col. EX Festività (W)')),
                ('pre_col_matricola', models.IntegerField(default=0, verbose_name='PRE: Col. Matricola')),
                ('pre_col_lunedi', models.IntegerField(default=1, verbose_name='PRE: Col. Inizio Lunedì (le altre 6 seguono)')),
            ],
            options={
                'verbose_name_plural': '3. Configurazioni Mappatura',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Studio Professionale')),
                ('sede', models.CharField(max_length=255, verbose_name='Sede Studio')),
                ('partita_iva', models.CharField(blank=True, max_length=11, null=True, verbose_name='Partita IVA')),
            ],
            options={
                'verbose_name': '1. Studio di Consulenza',
                'verbose_name_plural': '1. Studio di Consulenza (Unico)',
            },
        ),
        migrations.CreateModel(
            name='CaricamentoDati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operazione', models.DateTimeField(auto_now_add=True)),
                ('file_anagrafica', models.FileField(blank=True, null=True, upload_to='excel/', verbose_name='1. Anagrafica (XLS)')),
                ('file_retribuzioni', models.FileField(blank=True, null=True, upload_to='excel/', verbose_name='2. Retribuzioni (XLS)')),
                ('file_stacos', models.FileField(blank=True, null=True, upload_to='excel/', verbose_name='3. Stacos (XLS)')),
                ('file_ratei', models.FileField(blank=True, null=True, upload_to='excel/', verbose_name='4. Ratei (XLS)')),
                ('file_presenze', models.FileField(blank=True, null=True, upload_to='excel/', verbose_name='5. Presenze (XLS)')),
                ('elaborato', models.BooleanField(default=False)),
                ('mappatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafica.configurazionemappatura', verbose_name='Software GIS')),
            ],
            options={
                'verbose_name_plural': '6. Caricamento Dati Gestionale',
            },
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10, unique=True, verbose_name='Codice Azienda GIS')),
                ('ragione_sociale', models.CharField(max_length=255, verbose_name='Ragione Sociale')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aziende', to='anagrafica.studio', verbose_name='Studio')),
            ],
            options={
                'verbose_name_plural': '4. Aziende',
            },
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10, verbose_name='Matricola GIS')),
                ('cognome_nome', models.CharField(max_length=255, verbose_name='Cognome e Nome')),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('comune', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifica', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_contratto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo Det/Indet')),
                ('tipo_paga', models.CharField(default='Mensile', max_length=50, verbose_name='Tipo Paga')),
                ('perc_part_time', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='% Lavoro')),
                ('data_assunzione', models.DateField(blank=True, null=True, verbose_name='Assunzione')),
                ('data_cessazione', models.DateField(blank=True, null=True, verbose_name='Cessazione')),
                ('data_termine', models.DateField(blank=True, null=True, verbose_name='Fine Prevista/Proroga')),
                ('elemento_1', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('elemento_2', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('elemento_3', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('elemento_4', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('elemento_5', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('elemento_6', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('elemento_7', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('elemento_8', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('lordo_mensile_calcolato', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Lordo Mensile Calcolato')),
                ('costo_inps_ditta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='INPS Ditta (AH)')),
                ('costo_inail_ditta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='INAIL Ditta (AI)')),
                ('rateo_tfr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Rateo TFR')),
                ('ferie_residuo_ap', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Ferie Residue (L)')),
                ('permessi_residuo_ap', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Permessi Residui (O)')),
                ('rol_residuo_ap', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='ROL (S)')),
                ('ex_fest_residuo_ap', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='EX Festività (W)')),
                ('ore_lun', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Lun')),
                ('ore_mar', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Mar')),
                ('ore_mer', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Mer')),
                ('ore_gio', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Gio')),
                ('ore_ven', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Ven')),
                ('ore_sab', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Sab')),
                ('ore_dom', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Dom')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dipendenti', to='anagrafica.azienda', verbose_name='Azienda')),
                ('ccnl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafica.ccnl', verbose_name='CCNL')),
            ],
            options={
                'verbose_name_plural': '5. Anagrafica Dipendenti',
                'unique_together': {('azienda', 'codice')},
            },
        ),
    ]
