# Generated by Django 6.0.2 on 2026-02-23 23:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessioneImportazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operazione', models.DateTimeField(auto_now_add=True)),
                ('nome_file', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='azienda',
            options={'verbose_name_plural': '3. Aziende'},
        ),
        migrations.AlterModelOptions(
            name='caricamentodati',
            options={'verbose_name_plural': 'Caricamenti Manuali'},
        ),
        migrations.AlterModelOptions(
            name='configurazionemappatura',
            options={'verbose_name_plural': 'Mappature Software'},
        ),
        migrations.RemoveField(
            model_name='caricamentodati',
            name='elaborato',
        ),
        migrations.RemoveField(
            model_name='caricamentodati',
            name='file_presenze',
        ),
        migrations.RemoveField(
            model_name='caricamentodati',
            name='file_ratei',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_assunzione',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_azienda_cod',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_azienda_ragione',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_cessazione',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_comune',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_indirizzo',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_matricola',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_nominativo',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_perc_part_time',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_qualifica',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_termine',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_col_tipo_contratto',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ana_riga_inizio',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='pre_col_lunedi',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='pre_col_matricola',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='rat_col_exfest_ap',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='rat_col_ferie_ap',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='rat_col_matricola',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='rat_col_permessi_ap',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='rat_col_rol_ap',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ret_col_elementi_start',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ret_col_lordo_fatto',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ret_col_matricola',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ret_col_tipo_paga',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='ret_riga_inizio',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='sta_col_inail',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='sta_col_inps',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='sta_col_matricola',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='sta_col_tfr',
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dipendente',
            name='elemento_10',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='elemento_11',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='elemento_12',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='elemento_13',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='elemento_14',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='elemento_15',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='elemento_16',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='elemento_17',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='elemento_18',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='elemento_9',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='ex_fest_maturati',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='EX Fest Maturate'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='ferie_maturate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Ferie Maturate'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='permessi_maturati',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Permessi Maturati'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='rol_maturati',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='ROL Maturati'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='codice',
            field=models.CharField(max_length=20, unique=True, verbose_name='Codice Azienda GIS'),
        ),
        migrations.AlterField(
            model_name='caricamentodati',
            name='file_anagrafica',
            field=models.FileField(blank=True, null=True, upload_to='excel/'),
        ),
        migrations.AlterField(
            model_name='caricamentodati',
            name='file_retribuzioni',
            field=models.FileField(blank=True, null=True, upload_to='excel/'),
        ),
        migrations.AlterField(
            model_name='caricamentodati',
            name='file_stacos',
            field=models.FileField(blank=True, null=True, upload_to='excel/'),
        ),
        migrations.AlterField(
            model_name='configurazionemappatura',
            name='nome_software',
            field=models.CharField(default='Ranocchi GIS', max_length=100),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='codice',
            field=models.CharField(max_length=20, verbose_name='Matricola GIS'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='costo_inail_ditta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='INAIL Ditta (AI)'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='costo_inps_ditta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='INPS Ditta (AH)'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='elemento_1',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='elemento_2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='elemento_3',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='elemento_4',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='elemento_5',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='elemento_6',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='elemento_7',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='elemento_8',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ex_fest_residuo_ap',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='EX Festività (W)'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ferie_residuo_ap',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Ferie Residue (L)'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='lordo_mensile_calcolato',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Lordo Mensile Calcolato'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_dom',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Dom'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_gio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Gio'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_lun',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Lun'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_mar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Mar'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_mer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Mer'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_sab',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Sab'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_ven',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ven'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='permessi_residuo_ap',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Permessi Residui (O)'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='rateo_tfr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Rateo TFR'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='rol_residuo_ap',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='ROL (S)'),
        ),
        migrations.CreateModel(
            name='RecordStoricoDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricola', models.CharField(max_length=20)),
                ('nominativo', models.CharField(max_length=255)),
                ('codice_azienda', models.CharField(max_length=20)),
                ('ragione_sociale', models.CharField(max_length=255)),
                ('lordo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('netto_stimato', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='anagrafica.sessioneimportazione')),
            ],
        ),
    ]
