# Generated by Django 6.0.2 on 2026-02-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0002_sessioneimportazione_alter_azienda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_assunzione',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_azienda_cod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_azienda_ragione',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_cessazione',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_comune',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_indirizzo',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_matricola',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_nominativo',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_perc_part_time',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_qualifica',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_termine',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_tipo_contratto',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_riga_inizio',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='pre_col_lunedi',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='pre_col_matricola',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_exfest_ap',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_ferie_ap',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_matricola',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_permessi_ap',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_rol_ap',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ret_col_elementi_start',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ret_col_lordo_fatto',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ret_col_matricola',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ret_col_tipo_paga',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ret_riga_inizio',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='sta_col_inail',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='sta_col_inps',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='sta_col_matricola',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='sta_col_tfr',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='costo_inail_ditta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='costo_inps_ditta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ex_fest_maturati',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ex_fest_residuo_ap',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ferie_maturate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ferie_residuo_ap',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='lordo_mensile_calcolato',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_dom',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_gio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_lun',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_mar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_mer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_sab',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ore_ven',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='permessi_maturati',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='permessi_residuo_ap',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='rateo_tfr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='rol_maturati',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='rol_residuo_ap',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
