# Generated by Django 6.0.2 on 2026-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0003_configurazionemappatura_ana_col_assunzione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caricamentodati',
            name='file_presenze',
            field=models.FileField(blank=True, null=True, upload_to='excel/'),
        ),
        migrations.AddField(
            model_name='caricamentodati',
            name='file_ratei',
            field=models.FileField(blank=True, null=True, upload_to='excel/'),
        ),
    ]
