# Generated by Django 6.0.2 on 2026-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0004_caricamentodati_file_presenze_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='pre_col_lunedi',
        ),
        migrations.RemoveField(
            model_name='configurazionemappatura',
            name='pre_col_matricola',
        ),
        migrations.AlterField(
            model_name='caricamentodati',
            name='file_presenze',
            field=models.FileField(blank=True, null=True, upload_to='presenze_uploads/', verbose_name='Archivio Presenze Massivo (ZIP)'),
        ),
    ]
