# Generated by Django 6.0.2 on 2026-03-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0006_configurazionemappatura_ret_col_azienda_cod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studio',
            options={'verbose_name_plural': '1. Studio di Consulenza (Unico)'},
        ),
        migrations.RenameField(
            model_name='configurazionemappatura',
            old_name='rat_col_permessi_ap',
            new_name='rat_col_perm_ap',
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_livello',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_exfest_god',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_exfest_mat',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_exfest_res',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_ferie_god',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_ferie_mat',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_ferie_res',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_perm_god',
            field=models.IntegerField(default=13),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_perm_mat',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_perm_res',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_rol_god',
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_rol_mat',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_rol_res',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='ex_fest_goduti',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='ex_fest_residuo_attuale',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='ferie_godute',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='ferie_residuo_attuale',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='livello',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='permessi_goduti',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='permessi_residuo_attuale',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='rol_goduti',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='rol_residuo_attuale',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='codice',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='ragione_sociale',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aziende', to='anagrafica.studio'),
        ),
        migrations.AlterField(
            model_name='caricamentodati',
            name='file_presenze',
            field=models.FileField(blank=True, null=True, upload_to='presenze_uploads/', verbose_name='ZIP Presenze'),
        ),
        migrations.AlterField(
            model_name='caricamentodati',
            name='mappatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafica.configurazionemappatura'),
        ),
        migrations.AlterField(
            model_name='ccnl',
            name='divisore_orario_standard',
            field=models.DecimalField(decimal_places=2, default=173.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ccnl',
            name='magg_straordinario',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ccnl',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Contratto'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dipendenti', to='anagrafica.azienda'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ccnl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafica.ccnl'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='cognome_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='data_assunzione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='data_cessazione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='data_termine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='perc_part_time',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='tipo_contratto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='tipo_paga',
            field=models.CharField(default='Mensile', max_length=50),
        ),
        migrations.DeleteModel(
            name='RecordStoricoDipendente',
        ),
        migrations.DeleteModel(
            name='SessioneImportazione',
        ),
    ]
