# Generated by Django 6.0.2 on 2026-03-07 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0007_alter_studio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccnl',
            options={'verbose_name_plural': '2. Schede CCNL (Parametri)'},
        ),
        migrations.AddField(
            model_name='azienda',
            name='ccnl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafica.ccnl', verbose_name='CCNL Applicato'),
        ),
        migrations.AddField(
            model_name='ccnl',
            name='magg_domenicale',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='% Lavoro Domenicale'),
        ),
        migrations.AddField(
            model_name='ccnl',
            name='magg_festivo',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='% Lavoro Festivo'),
        ),
        migrations.AddField(
            model_name='ccnl',
            name='magg_supplementare',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Lavoro Suppl.'),
        ),
        migrations.AddField(
            model_name='ccnl',
            name='mat_exfest_mese',
            field=models.DecimalField(decimal_places=3, default=2.666, max_digits=6, verbose_name='Ex Fest maturate/mese'),
        ),
        migrations.AddField(
            model_name='ccnl',
            name='mat_ferie_mese',
            field=models.DecimalField(decimal_places=3, default=2.166, max_digits=6, verbose_name='Ferie maturate/mese'),
        ),
        migrations.AddField(
            model_name='ccnl',
            name='mat_rol_mese',
            field=models.DecimalField(decimal_places=3, default=4.666, max_digits=6, verbose_name='ROL maturati/mese'),
        ),
        migrations.AlterField(
            model_name='ccnl',
            name='divisore_orario_standard',
            field=models.DecimalField(decimal_places=2, default=173.0, max_digits=6, verbose_name='Divisore Contrattuale'),
        ),
        migrations.AlterField(
            model_name='ccnl',
            name='magg_straordinario',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='% Lavoro Straord.'),
        ),
        migrations.AlterField(
            model_name='dipendente',
            name='ccnl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafica.ccnl', verbose_name='CCNL Eccezione'),
        ),
    ]
