# Generated by Django 6.0.2 on 2026-03-07 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0008_alter_ccnl_options_azienda_ccnl_ccnl_magg_domenicale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaleAssenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10, unique=True, verbose_name='Codice GIS (es. *FE)')),
                ('descrizione', models.CharField(max_length=255)),
                ('tipo_causale', models.CharField(choices=[('LAVORO', 'Lavoro Ordinario'), ('ASSENZA', 'Assenza Retribuita'), ('NON_RET', 'Assenza Non Retribuita'), ('FEST', 'Festività Goduta')], default='ASSENZA', max_length=20)),
                ('incide_su_rateo', models.CharField(choices=[('FERIE', 'Ferie'), ('ROL', 'ROL'), ('PERM', 'Permessi'), ('NESSUNO', 'Nessuno')], default='NESSUNO', max_length=20)),
            ],
            options={
                'verbose_name_plural': '6. Causali GIS Ranocchi',
            },
        ),
        migrations.AddField(
            model_name='azienda',
            name='giorno_patrono',
            field=models.IntegerField(blank=True, help_text='GG', null=True),
        ),
        migrations.AddField(
            model_name='azienda',
            name='mese_patrono',
            field=models.IntegerField(blank=True, help_text='MM', null=True),
        ),
        migrations.AddField(
            model_name='caricamentodati',
            name='file_causali_gis',
            field=models.FileField(blank=True, null=True, upload_to='causali/', verbose_name='CSV Causali Ranocchi'),
        ),
        migrations.AddField(
            model_name='ccnl',
            name='coeff_netto_stima',
            field=models.DecimalField(decimal_places=2, default=0.75, help_text='Coefficiente per stima netto (es. 0.75)', max_digits=4),
        ),
        migrations.AddField(
            model_name='ccnl',
            name='magg_notturna',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='% Lavoro Notturno'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='banca_ore_residuo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Residuo Banca Ore'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='notturno_standard',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Ore Notturne fisse'),
        ),
        migrations.CreateModel(
            name='PresenzaGiornaliera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ore_lavorate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('di_cui_notturne', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('straordinarie', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_festivo', models.BooleanField(default=False)),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenze', to='anagrafica.dipendente')),
            ],
            options={
                'verbose_name_plural': '7. Registro Presenze Giornaliero',
                'unique_together': {('dipendente', 'data')},
            },
        ),
        migrations.CreateModel(
            name='EventoAssenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('causale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafica.causaleassenza')),
                ('giornata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='anagrafica.presenzagiornaliera')),
            ],
            options={
                'verbose_name_plural': '8. Eventi Assenza (Righe Extra CSV)',
            },
        ),
    ]
