# Generated by Django 6.0.2 on 2026-03-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0009_causaleassenza_azienda_giorno_patrono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionemappatura',
            name='pre_col_matricola',
            field=models.IntegerField(default=0, verbose_name='Colonna Matricola (PRE)'),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='pre_col_tipo',
            field=models.IntegerField(default=2, verbose_name='Colonna Tipo Riga (PRE)'),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='pre_riga_inizio',
            field=models.IntegerField(default=4, verbose_name='Riga Inizio Presenze'),
        ),
    ]
