# Generated by Django 6.0.2 on 2026-03-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0010_configurazionemappatura_pre_col_matricola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionemappatura',
            name='ana_col_sede_lavoro',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='rat_col_azienda_cod',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configurazionemappatura',
            name='sta_col_azienda_cod',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='sede_lavoro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
