# Generated by Django 6.0.2 on 2026-03-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0011_configurazionemappatura_ana_col_sede_lavoro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionemappatura',
            name='pre_col_azienda_cod',
            field=models.IntegerField(default=-1, help_text='-1 se da intestazione'),
        ),
        migrations.AlterField(
            model_name='configurazionemappatura',
            name='rat_col_azienda_cod',
            field=models.IntegerField(default=1, verbose_name='Col. Azienda (RAT)'),
        ),
        migrations.AlterField(
            model_name='configurazionemappatura',
            name='sta_col_azienda_cod',
            field=models.IntegerField(default=2, verbose_name='Col. Azienda (STA)'),
        ),
    ]
