# Generated by Django 6.0.2 on 2026-03-11 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0012_configurazionemappatura_pre_col_azienda_cod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='utente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='azienda_gestita', to=settings.AUTH_USER_MODEL, verbose_name='Utente di Accesso (Cliente)'),
        ),
    ]
