# Generated by Django 6.0.2 on 2026-03-14 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0013_azienda_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccnl',
            name='magg_festivo',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='% Lavoro Notturno'),
        ),
        migrations.CreateModel(
            name='NotaMensileAzienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('mese', models.IntegerField()),
                ('testo', models.TextField(blank=True, null=True, verbose_name='Note e Rimborsi')),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_mensili', to='anagrafica.azienda')),
            ],
            options={
                'verbose_name_plural': '9. Note Mensili Aziende',
                'unique_together': {('azienda', 'anno', 'mese')},
            },
        ),
    ]
