# Generated by Django 6.0.2 on 2026-03-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0014_alter_ccnl_magg_festivo_notamensileazienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccnl',
            name='mensilita',
            field=models.IntegerField(default=13, verbose_name='Numero Mensilità (13 o 14)'),
        ),
        migrations.AlterField(
            model_name='ccnl',
            name='magg_festivo',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='% Lavoro Festivo'),
        ),
    ]
