# Generated by Django 6.0.2 on 2026-03-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0015_ccnl_mensilita_alter_ccnl_magg_festivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='loghi_aziende/', verbose_name='Logo Azienda'),
        ),
        migrations.AddField(
            model_name='presenzagiornaliera',
            name='is_riposo',
            field=models.BooleanField(default=False, verbose_name='Forza Riposo'),
        ),
        migrations.AddField(
            model_name='presenzagiornaliera',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note Spostamento/Turno'),
        ),
        migrations.AddField(
            model_name='studio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='loghi_studio/', verbose_name='Logo Studio'),
        ),
    ]
