# Generated by Django 6.0.2 on 2026-03-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0016_azienda_logo_presenzagiornaliera_is_riposo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='email_amministrazione',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Amministrazione'),
        ),
    ]
